/*
 * This file is a part of TGx101, a modification of Telegram X
 * Copyright © 2026 1vank0 (https://github.com/Ivan-k0/plumagram-android)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
package org.thunderdog.challegram.core;

import android.util.SparseArray;

import androidx.annotation.Nullable;

import org.drinkless.tdlib.TdApi;
import org.thunderdog.challegram.R;

/**
 * Russian texts for TGx101's own strings.
 *
 * Telegram's cloud language packs don't know the mod's keys, so without this every mod
 * string would stay English. English (res/values/strings.xml) is used for any other
 * language picked in the app.
 */
final class Tgx101Strings {
  private static final SparseArray<String> RU = new SparseArray<>();

  static {
    RU.put(R.string.Tgx101Settings, "MagiX");
    RU.put(R.string.Tgx101BarCut, "Вырезать");
    RU.put(R.string.Tgx101BarPaste, "Вставить");
    RU.put(R.string.Tgx101BarApps, "Другие приложения (Перевести, Поиск…)");
    RU.put(R.string.Tgx101BarMessageSection, "В сообщении");
    RU.put(R.string.Tgx101BarInputSection, "Поле ввода — верхний ряд");
    RU.put(R.string.Tgx101BarFormatSection, "Поле ввода — кнопки оформления");
    RU.put(R.string.Tgx101BarHint, "Нажмите на пункт, чтобы передвинуть или скрыть его. «В сообщении» — строка над текстом, выделенным в сообщении; строки поля ввода появляются при выделении текста в поле ввода.");
    RU.put(R.string.Tgx101InputSection, "Поле ввода");
    RU.put(R.string.Tgx101InputSectionHint, "Порядок кнопок в строках, которые появляются при выделении текста — в сообщении и в поле ввода; ненужные можно скрыть.");
    RU.put(R.string.Tgx101MenuSelectText, "Редактор / Цитировать (чужие сообщения)");
    RU.put(R.string.Tgx101MenuEditorOwn, "Редактор (свои сообщения)");
    RU.put(R.string.Tgx101MenuMessagesFrom, "Сообщения от участника");
    RU.put(R.string.Tgx101MenuInMore, "В «Ещё»");
    RU.put(R.string.Tgx101MenuShowInMenu, "Показывать в меню");
    RU.put(R.string.Tgx101MenuMoveToMore, "Перенести в «Ещё…»");
    RU.put(R.string.Tgx101Filters, "Фильтры сообщений");
    RU.put(R.string.Tgx101FiltersEnabled, "Скрывать сообщения по фильтрам");
    RU.put(R.string.Tgx101FiltersHeader, "Фильтры");
    RU.put(R.string.Tgx101FiltersAdd, "Добавить фильтр");
    RU.put(R.string.Tgx101FiltersOff, "Выкл");
    RU.put(R.string.Tgx101FiltersHint, "Работает только на этом телефоне: сообщения не удаляются, и никто не видит, что вы их скрыли. Скрытое сообщение становится полоской — нажатие показывает его. Свои сообщения и спонсорская реклама Telegram не скрываются. Изменения действуют на чаты, открытые после них.");
    RU.put(R.string.Tgx101FilterNew, "Новый фильтр");
    RU.put(R.string.Tgx101FilterEdit, "Фильтр");
    RU.put(R.string.Tgx101FilterText, "Слово, фраза или выражение");
    RU.put(R.string.Tgx101FilterRegex, "Регулярное выражение");
    RU.put(R.string.Tgx101FilterCase, "Учитывать регистр");
    RU.put(R.string.Tgx101FilterWholeWord, "Только целое слово");
    RU.put(R.string.Tgx101FilterRegexHint, "Без «Регулярного выражения» текст ищется как есть. С ним, например, «розыгрыш|конкурс» скрывает сообщения с любым из этих слов.");
    RU.put(R.string.Tgx101FilterWhere, "Где применять");
    RU.put(R.string.Tgx101FilterScopeAll, "Все чаты");
    RU.put(R.string.Tgx101FilterScopeChannels, "Только каналы");
    RU.put(R.string.Tgx101FilterScopeChannelsGroups, "Каналы и группы");
    RU.put(R.string.Tgx101FilterScopeChat, "Только «%1$s»");
    RU.put(R.string.Tgx101FilterCheckAuthor, "Также имя автора / источника");
    RU.put(R.string.Tgx101FilterCheckHint, "Текст и подписи к медиа проверяются всегда. Имя автора — это отправитель, подпись поста и источник пересланного сообщения.");
    RU.put(R.string.Tgx101FilterDelete, "Удалить фильтр");
    RU.put(R.string.Tgx101FilterBadRegex, "Ошибка в выражении: %1$s");
    RU.put(R.string.Tgx101FilterHiddenBy, "Скрыто фильтром «%1$s» · Показать");
    RU.put(R.string.Tgx101FilterSimilar, "Скрывать похожие…");
    RU.put(R.string.RecordingAndPhotos, "Запись и фото");
    RU.put(R.string.PauseMediaOnRecord, "Пауза музыки при записи и голосовых");
    RU.put(R.string.SendPhotosInHD, "Отправлять фото в HD");
    RU.put(R.string.WriteContactsToPhoneBook, "Контакты Telegram в телефонной книге");
    RU.put(R.string.TextSelection, "Выделение текста");
    RU.put(R.string.SelectTextToQuoteSetting, "Выделение текста для цитаты в ответе");
    RU.put(R.string.SelectText, "Выделить текст");
    RU.put(R.string.SelectTextToQuoteHint, "Выделите часть сообщения и нажмите «Ответить», чтобы процитировать только её");
    RU.put(R.string.BackgroundConnection, "Фоновое соединение");
    RU.put(R.string.KeepAliveConnectionSetting, "Держать соединение в фоне");
    RU.put(R.string.KeepAliveConnectionHint, "Приложение остаётся на связи с Telegram, даже когда закрыто, и сообщения приходят сразу, без push-сервисов Google. Чтобы скрыть уведомление службы, зажмите его и отключите.");
    RU.put(R.string.KeepAliveChannel, "Фоновое соединение");
    RU.put(R.string.KeepAliveNotification, "Подключено к Telegram");
    RU.put(R.string.RoundVideoQuality, "Качество кружков");
    RU.put(R.string.RoundVideoQualitySd, "Стандарт (240p)");
    RU.put(R.string.RoundVideoQualityHq, "HQ (320p)");
    RU.put(R.string.RoundVideoQualityHigh, "Высокое (480p)");
    RU.put(R.string.RoundVideoQualityMax, "Максимум (640p)");
    RU.put(R.string.RoundVideoQualityHint, "Примерный вес минуты: Стандарт 3 МБ, HQ 5 МБ, Высокое 9 МБ, Максимум 10–11 МБ. Telegram принимает кружки до 640p и до 12 МБ, поэтому при любом выборе кружок уходит кружком; если кружок подходит к 12 МБ, запись останавливается сама.");
    RU.put(R.string.RoundStabilization, "Стабилизация кружков");
    RU.put(R.string.RoundStabilizationOff, "Выкл");
    RU.put(R.string.RoundStabilizationSystem, "Системная");
    RU.put(R.string.RoundStabilizationGyro, "Гироскоп");
    RU.put(R.string.RoundStabilizationCamera2, "Camera2");
    RU.put(R.string.RoundStabilizationHint, "Телефоны ведут себя по-разному — выберите, что лучше работает на вашем. Системная: встроенная стабилизация камеры, на многих телефонах эффекта нет. Гироскоп: приложение гасит дрожание рук по гироскопу, слегка приближая картинку; работает на любом телефоне. Camera2: собственная стабилизация превью телефона на Android 13+; если телефон её не поддерживает, включается «Гироскоп».");
    RU.put(R.string.Transcribe, "Расшифровать");
    RU.put(R.string.TranscriptionClose, "Закрыть");
    RU.put(R.string.TranscriptionInProgress, "Распознаю речь…");
    RU.put(R.string.TranscriptionEmpty, "Речь не распознана.");
    RU.put(R.string.TranscriptionFailed, "Не удалось распознать речь.");
    RU.put(R.string.TranscriptionUnavailable, "Telegram не смог расшифровать сообщение (нужен Premium или исчерпан недельный лимит), а распознавание на телефоне недоступно (нужен Android 13+ и сервис распознавания речи).");
    RU.put(R.string.Tgx101TranscriptionModelDownloading, "На телефон скачивается пакет распознавания речи для этого языка. Попробуйте через минуту");
    RU.put(R.string.TranscriptionLanguageUnavailable, "Распознаватель речи на телефоне не поддерживает этот язык. Скачайте его в системных настройках голосового ввода.");
    RU.put(R.string.ChatListSection, "Чаты");
    RU.put(R.string.Tgx101Topics, "Темы");
    RU.put(R.string.Tgx101TopicNew, "Новая тема");
    RU.put(R.string.Tgx101TopicNameHint, "Название темы");
    RU.put(R.string.Tgx101TopicsAllMessages, "Все сообщения одной лентой");
    RU.put(R.string.Tgx101TopicsShow, "Показать темы");
    RU.put(R.string.Tgx101TopicEdit, "Переименовать тему");
    RU.put(R.string.Tgx101TopicPin, "Закрепить тему");
    RU.put(R.string.Tgx101TopicUnpin, "Открепить тему");
    RU.put(R.string.Tgx101TopicClose, "Закрыть тему");
    RU.put(R.string.Tgx101TopicReopen, "Открыть тему снова");
    RU.put(R.string.Tgx101TopicHide, "Скрыть «Общее»");
    RU.put(R.string.Tgx101TopicUnhide, "Показать «Общее»");
    RU.put(R.string.Tgx101TopicDelete, "Удалить тему");
    RU.put(R.string.Tgx101TopicDeleteConfirm, "Удалить тему «%1$s» со всеми сообщениями?");
    RU.put(R.string.Tgx101TopicsEmpty, "Тем пока нет");
    RU.put(R.string.Tgx101TopicNoMessages, "Сообщений пока нет");
    RU.put(R.string.Tgx101TopicHidden, "скрыта");
    RU.put(R.string.BigEmojiSize, "Размер эмодзи и стикеров");
    RU.put(R.string.BigEmojiSizeOff, "Выкл (обычные эмодзи)");
    RU.put(R.string.BigEmojiSize60, "Маленькие");
    RU.put(R.string.BigEmojiSize80, "Средние");
    RU.put(R.string.BigEmojiSize100, "Стандарт");
    RU.put(R.string.BigEmojiSize125, "Крупные");
    RU.put(R.string.BigEmojiSizeHint, "Размер стикеров и сообщений, состоящих только из эмодзи. «Выкл» показывает эмодзи обычным текстом в пузыре, стикеры остаются стандартного размера. Это та же настройка, что «Большие эмодзи» в разделе «Стикеры и эмодзи». Применяется к чатам, открытым после изменения.");
    RU.put(R.string.PullToSearch, "Поиск свайпом вниз");
    RU.put(R.string.Tgx101NotificationPlane, "Самолётик Telegram в уведомлениях");
    RU.put(R.string.Tgx101CallSpeakerOn, "Динамик");
    RU.put(R.string.Tgx101CallSpeakerOff, "Выключить динамик");
    RU.put(R.string.Tgx101TextSection, "Текст");
    RU.put(R.string.Tgx101ChatListTextSize, "Размер текста в списке чатов");
    RU.put(R.string.Tgx101ChatListTextSize100, "Стандарт");
    RU.put(R.string.Tgx101ChatListTextSize110, "Крупнее");
    RU.put(R.string.Tgx101ChatListTextSize120, "Крупный");
    RU.put(R.string.Tgx101ChatListTextSize130, "Очень крупный");
    RU.put(R.string.Tgx101TextWeight, "Толщина текста");
    RU.put(R.string.Tgx101TextEditorSetting, "Изменять сообщения в окне с кнопками оформления");
    RU.put(R.string.Tgx101EditorEdit, "Изменить");
    RU.put(R.string.Tgx101EditorQuoteTitle, "Цитировать");
    RU.put(R.string.Tgx101QuoteAction, "Цитировать");
    RU.put(R.string.Tgx101EditorTabStyle, "Стиль");
    RU.put(R.string.Tgx101EditorTabBlocks, "Блоки");
    RU.put(R.string.Tgx101EditorTabEdit, "Правка");
    RU.put(R.string.Tgx101EditorBold, "Жирный");
    RU.put(R.string.Tgx101EditorItalic, "Курсив");
    RU.put(R.string.Tgx101EditorUnderline, "Подчёркн.");
    RU.put(R.string.Tgx101EditorStrike, "Зачёркн.");
    RU.put(R.string.Tgx101EditorQuote, "Цитата");
    RU.put(R.string.Tgx101EditorMono, "Моно");
    RU.put(R.string.Tgx101EditorSpoiler, "Призрак");
    RU.put(R.string.Tgx101EditorLink, "Ссылка");
    RU.put(R.string.Tgx101EditorPlain, "Обычный");
    RU.put(R.string.Tgx101EditorSelectAll, "Выбрать всё");
    RU.put(R.string.Tgx101EditorSelectAllShort, "Всё");
    RU.put(R.string.Tgx101EditorCopy, "Скопировать");
    RU.put(R.string.Tgx101EditorCopyAll, "Скопировать всё");
    RU.put(R.string.Tgx101EditorSave, "Сохранить");
    RU.put(R.string.Tgx101EditorReplyQuote, "Ответить цитатой");
    RU.put(R.string.Tgx101EditorSelectFirst, "Сначала выделите текст");
    RU.put(R.string.Tgx101EditorChars, "%1$d симв.");
    RU.put(R.string.Tgx101CallPopupSubtitle, "PlumaGram · входящий звонок");
    RU.put(R.string.Tgx101RawPreviewOpening, "Открываю RAW-фото…");
    RU.put(R.string.Tgx101CallBarSetting, "Плашка текущего звонка над чатами");
    RU.put(R.string.Tgx101EditorMenu, "Редактор");
    RU.put(R.string.Tgx101FormatMenu, "Кнопки мини-редактора");
    RU.put(R.string.Tgx101FormatMenuHint, "Пункты оформления, которые видны при выделении текста в поле ввода — после «Копировать», «Вставить», «Выбрать всё». Нажмите на пункт, чтобы переместить или скрыть его.");
    RU.put(R.string.Tgx101FormatHidden, "скрыт");
    RU.put(R.string.Tgx101FormatShow, "Показать");
    RU.put(R.string.Tgx101FormatHide, "Скрыть");
    RU.put(R.string.Tgx101FormatMonoShort, "Моно");
    RU.put(R.string.Tgx101SelectAllFull, "Выделить всё");
    RU.put(R.string.Tgx101Undo, "Отменить");
    RU.put(R.string.Tgx101NothingToUndo, "Нечего отменять");
    RU.put(R.string.Tgx101RingRampTime, "Время нарастания звонка");
    RU.put(R.string.Tgx101RingRampSeconds, "%1$d с");
    RU.put(R.string.Tgx101RingRampHint, "За сколько секунд мелодия входящего звонка вырастает от тихой до полной громкости.");
    RU.put(R.string.Tgx101Font, "Шрифт");
    RU.put(R.string.Tgx101FontSystem, "Системный (как в настройках телефона)");
    RU.put(R.string.Tgx101FontRoboto, "Roboto (как в Telegram X)");
    RU.put(R.string.Tgx101FontHint, "Меняется только начертание; размер и толщина текста остаются как настроены. Применится после перезапуска приложения.");
    RU.put(R.string.Tgx101FontRestart, "Перезапустите приложение, чтобы применить шрифт");
    RU.put(R.string.Tgx101TextWeightNormal, "Обычная");
    RU.put(R.string.Tgx101TextWeightSlightlyBolder, "Чуть жирнее");
    RU.put(R.string.Tgx101TextWeightSemibold, "Полужирная");
    RU.put(R.string.Tgx101TextWeightHint, "Сообщения, список чатов и остальной обычный текст. Заголовки остаются жирнее текста. Применится после перезапуска приложения.");
    RU.put(R.string.Tgx101TextWeightRestart, "Перезапустите приложение, чтобы применить толщину текста");
    RU.put(R.string.Tgx101MessageMenuSection, "Меню сообщения");
    RU.put(R.string.Tgx101MessageMenu, "Компактное меню сообщения");
    RU.put(R.string.Tgx101MessageMenuHand, "Меню под руку");
    RU.put(R.string.Tgx101MessageMenuHandRight, "Правую");
    RU.put(R.string.Tgx101MessageMenuHandLeft, "Левую");
    RU.put(R.string.Tgx101MessageMenuOrder, "Пункты меню сообщения");
    RU.put(R.string.Tgx101MessageMenuOrderHint, "Нажмите на пункт, чтобы передвинуть его, скрыть или перенести в «Ещё…» (там же, где «Удалить из кэша»). Пункты, которых нет у сообщения, пропускаются. «Удалить» и остальные пункты не меняются: «Удалить» всегда внизу.");
    RU.put(R.string.Tgx101MessageMenuOrderReset, "Вернуть порядок по умолчанию");
    RU.put(R.string.Tgx101MoveToTop, "В самый верх");
    RU.put(R.string.Tgx101MoveUp, "Выше");
    RU.put(R.string.Tgx101MoveDown, "Ниже");
    RU.put(R.string.Tgx101MoveToBottom, "В самый низ");
    RU.put(R.string.Tgx101ReadDateUnread, "Ещё не прочитано");
    RU.put(R.string.Tgx101ReadDateRead, "Прочитано");
    RU.put(R.string.Tgx101ReadDateHidden, "Время прочтения скрыто");
    RU.put(R.string.Tgx101DeleteMore, "Другие действия…");
    RU.put(R.string.Tgx101Channel, "Канал PlumaGram");
    RU.put(R.string.Tgx101BottomGap, "Отступ под полем ввода и меню");
    RU.put(R.string.PullToSearchHint, "Когда список чатов уже в самом верху, ещё один свайп вниз открывает поиск. Отступ под полем ввода и меню: поднимает их на 16 dp над нижним краем экрана, чтобы они не лежали на полоске жестов. Только при навигации жестами: с кнопками навигации отступа нет.");
    RU.put(R.string.AttachFromMenu, "Прикрепить");
    RU.put(R.string.PendingAttachment, "Вложение");
    RU.put(R.string.SavedTags, "Теги");
    RU.put(R.string.SavedTagSubtitle, "тег %1$s");
    RU.put(R.string.SavedTagsInfo, "Реакции в Избранном работают как теги. Выберите тег, чтобы увидеть только отмеченные им сообщения.");
    RU.put(R.string.SavedTagsInfoPartial, "Реакции в Избранном работают как теги. Показаны теги из последних 3000 сообщений.");
    RU.put(R.string.SavedTagsEmpty, "В Избранном нет сообщений с реакциями. Поставьте реакцию на сообщение, чтобы отметить его тегом.");
    RU.put(R.string.SavedTagsScanning, "Ищу теги в Избранном…");
    RU.put(R.string.ChannelsSection, "Каналы");
    RU.put(R.string.ShowDiscussButton, "Кнопка «Обсудить»");
    RU.put(R.string.Tgx101Premium, "Telegram Premium");
    RU.put(R.string.Tgx101VideoCall, "Видеозвонок");
    RU.put(R.string.Tgx101VideoWaitCall, "Камеру можно включить, когда собеседник ответит");
    RU.put(R.string.Tgx101VideoNoCamera, "Для видео нужен доступ к камере");
    RU.put(R.string.Tgx101WebProxyAdd, "Добавить WEB-прокси");
    RU.put(R.string.Tgx101WebProxyAddHint, "Для провайдера WEB-прокси выглядит как обычный сайт: трафик Telegram идёт по HTTPS через сайт прокси. Введите адрес (site.com или site.com/путь) и секрет от владельца прокси.");
    RU.put(R.string.Tgx101WebProxyAddress, "Адрес, например proxy.example.com");
    RU.put(R.string.Tgx101WebProxySecret, "Секрет");
    RU.put(R.string.Tgx101WebProxyConnect, "Подключить");
    RU.put(R.string.Tgx101WebProxyConfirm, "Подключить WEB-прокси %1$s?\nТрафик Telegram пойдёт по HTTPS через этот сайт.");
    RU.put(R.string.Tgx101WebProxyAdded, "WEB-прокси добавлен: %1$s");
    RU.put(R.string.Tgx101WebProxyInvalid, "Неверный адрес или секрет WEB-прокси");
    RU.put(R.string.Tgx101WebProxyUnsupported, "Для WEB-прокси нужен Android 5.0+ и свежий Android System WebView");
    RU.put(R.string.Tgx101VoiceChat, "Голосовой чат");
    RU.put(R.string.Tgx101VoiceChatJoin, "Голосовой чат");
    RU.put(R.string.Tgx101VoiceChatStart, "Начать голосовой чат");
    RU.put(R.string.Tgx101VoiceChatLeave, "Выйти");
    RU.put(R.string.Tgx101VoiceChatEndForAll, "Завершить для всех");
    RU.put(R.string.Tgx101VoiceChatSpeaker, "Динамик");
    RU.put(R.string.Tgx101VoiceChatMicOn, "Микрофон включён");
    RU.put(R.string.Tgx101VoiceChatMicOff, "Микрофон выключен");
    RU.put(R.string.Tgx101VoiceChatListening, "слушает");
    RU.put(R.string.Tgx101VoiceChatSpeaking, "говорит");
    RU.put(R.string.Tgx101VoiceChatYou, "%1$s (вы)");
    RU.put(R.string.Tgx101VoiceChatConnecting, "Подключение…");
    RU.put(R.string.Tgx101VoiceChatParticipantsCount, "Участников: %1$d");
    RU.put(R.string.Tgx101VoiceChatEnded, "Голосовой чат завершён");
    RU.put(R.string.Tgx101VoiceChatFailed, "Не удалось подключиться к голосовому чату: %1$s");
    RU.put(R.string.Tgx101VoiceChatNoMic, "Для голосового чата нужен доступ к микрофону");
    RU.put(R.string.Tgx101VoiceChatMutedByAdmin, "Администратор выключил вам микрофон");
    RU.put(R.string.Tgx101CardTitle, "Банковская карта");
    RU.put(R.string.Tgx101CardNotice, "Данные карты видит только платёжная система — %1$s. Ни Telegram, ни %2$s, ни PlumaGram их не получают и не сохраняют. Деньги идут владельцу %2$s.");
    RU.put(R.string.Tgx101CardNumber, "Номер карты");
    RU.put(R.string.Tgx101CardExpiry, "ММ/ГГ");
    RU.put(R.string.Tgx101CardCvc, "CVC / CVV");
    RU.put(R.string.Tgx101CardName, "Имя на карте");
    RU.put(R.string.Tgx101CardCountry, "Код страны (например, UA)");
    RU.put(R.string.Tgx101CardZip, "Почтовый индекс");
    RU.put(R.string.Tgx101CardNext, "Далее");
    RU.put(R.string.Tgx101CardInvalid, "Проверьте данные карты");
    RU.put(R.string.Tgx101CardProcessing, "Проверяем карту…");
    RU.put(R.string.Tgx101CardConnectionFailed, "Платёжная система не приняла карту или не ответила. Попробуйте ещё раз.");
    RU.put(R.string.Tgx101CardConfirm, "Оплатить %1$s за «%2$s» картой? Данные карты уходят напрямую в платёжную систему и не сохраняются.");
    RU.put(R.string.Tgx101CardShippingUnsupported, "Этот счёт требует адрес доставки, такое PlumaGram пока оплатить не может");
    RU.put(R.string.Tgx101OrderTitle, "Данные для оплаты");
    RU.put(R.string.Tgx101OrderName, "Имя");
    RU.put(R.string.Tgx101OrderPhone, "Телефон");
    RU.put(R.string.Tgx101OrderEmail, "Эл. почта");
    RU.put(R.string.Tgx101PremiumBuy, "Купить себе");
    RU.put(R.string.Tgx101PremiumCurrent, "текущий");
    RU.put(R.string.Tgx101PremiumFragment, "Купить на Fragment (TON)");
    RU.put(R.string.Tgx101PremiumActive, "Premium активен.");
    RU.put(R.string.Tgx101PremiumInactive, "Premium не активен.");
    RU.put(R.string.Tgx101PremiumBuyHint, "PlumaGram не может платить через Google Play. Срок подписки открывает @PremiumBot, он пришлёт счёт для оплаты картой; на Fragment Premium покупается за TON на ваш ник.");
    RU.put(R.string.Tgx101PremiumNoLink, "Для этого варианта Telegram не дал ссылку на оплату");
    RU.put(R.string.Tgx101PremiumGift, "Подарок");
    RU.put(R.string.Tgx101PremiumGiftStars, "Подарить Premium за звёзды");
    RU.put(R.string.Tgx101PremiumGiftHint, "За звёзды Premium можно только подарить другому человеку, себе купить нельзя.");
    RU.put(R.string.Tgx101PremiumGiftPickUser, "Выберите чат с человеком");
    RU.put(R.string.Tgx101PremiumGiftConfirm, "Подарить Telegram Premium: %1$s.\nНа балансе: %2$s");
    RU.put(R.string.Tgx101PremiumGiftUnavailable, "Подарить Premium за звёзды сейчас нельзя");
    RU.put(R.string.Tgx101PremiumGiftSent, "Premium подарен");
    RU.put(R.string.Tgx101CallsSection, "Звонки");
    RU.put(R.string.Tgx101CallPhoto, "Фото собеседника");
    RU.put(R.string.Tgx101CallPhotoCircle, "Круг");
    RU.put(R.string.Tgx101CallPhotoFullScreen, "На весь экран (как раньше)");
    RU.put(R.string.Tgx101CallPhotoNone, "Не показывать");
    RU.put(R.string.Tgx101CallPattern, "Узор из самолётиков");
    RU.put(R.string.Tgx101RingRamp, "Нарастающая громкость звонка");
    RU.put(R.string.Tgx101MenuToGallery, "В галерею");
    RU.put(R.string.Tgx101MenuToOriginal, "К оригиналу");
    RU.put(R.string.Tgx101FloatingInput, "Плавающее поле ввода");
    RU.put(R.string.Tgx101CameraInAttach, "Камера в скрепке");
    RU.put(R.string.Tgx101AttachCamera, "Камера");
    RU.put(R.string.Tgx101VoiceQueue, "Голосовые подряд");
    RU.put(R.string.Tgx101VoiceQueueAll, "Все (как сейчас)");
    RU.put(R.string.Tgx101VoiceQueueSkipOwn, "Пропускать свои");
    RU.put(R.string.Tgx101TapMode, "Двойной тап");
    RU.put(R.string.Tgx101TapModeStock, "Выкл (как сейчас)");
    RU.put(R.string.Tgx101TapModeDouble, "Двойной тап — лайк");
    RU.put(R.string.Tgx101TapModeDoubleSwipe, "Двойной тап и свайп — лайк");
    RU.put(R.string.Tgx101TapModeHint, "Двойной тап ставит реакцию №1 из быстрых реакций. В режиме «Двойной тап — лайк» свайп только отвечает. Долгое нажатие выделяет сообщение, повторное долгое нажатие открывает выделение текста.");
    RU.put(R.string.Tgx101CallMic, "Микрофон");
    RU.put(R.string.Tgx101CallVideoButton, "Видео");
    RU.put(R.string.Tgx101CallSpeaker, "Динамик");
    RU.put(R.string.Tgx101CallChat, "Чат");
    RU.put(R.string.Tgx101CallAudioOutput, "Аудиовыход");
    RU.put(R.string.Tgx101CallEnd, "Завершить");
    RU.put(R.string.Tgx101AudioPhone, "Телефон");
    RU.put(R.string.Tgx101AudioHeadset, "Гарнитура");
    RU.put(R.string.Tgx101AudioBluetooth, "Bluetooth");
    RU.put(R.string.Tgx101CallDecline, "Отклонить");
    RU.put(R.string.Tgx101CallMessage, "Сообщение");
    RU.put(R.string.Tgx101CallSilence, "Без звука");
    RU.put(R.string.Tgx101CallAnswer, "Ответить");
    RU.put(R.string.Tgx101IncomingCall, "Входящий вызов");
    RU.put(R.string.Tgx101NewCallScreen, "Новый экран звонка");
    RU.put(R.string.Tgx101QuickReplies, "Быстрые ответы на звонок");
    RU.put(R.string.Tgx101QuickRepliesHint, "На входящем звонке кнопка «Сообщение» предлагает первые три: звонок отклоняется, и ответ сразу уходит собеседнику, даже с экрана блокировки.");
    RU.put(R.string.Tgx101QuickReply1, "Не могу говорить, перезвоню");
    RU.put(R.string.Tgx101QuickReply2, "Перезвоню позже");
    RU.put(R.string.Tgx101QuickReply3, "Напишите, пожалуйста");
    RU.put(R.string.Tgx101QuickReply4, "Я за рулём");
    RU.put(R.string.Tgx101QuickReply5, "Я на встрече");
    RU.put(R.string.Tgx101QuickReplyN, "Ответ %1$d");
    RU.put(R.string.Tgx101CallPatternHint, "Круг — чёткое фото под именем. На весь экран — прежний дизайн Telegram X. Узор из бумажных самолётиков еле заметный и неподвижный; за фото на весь экран его не видно.");
    RU.put(R.string.ShowChannelMuteButton, "Кнопка уведомлений и колокольчик");
    RU.put(R.string.Tgx101TranslateSection, "Перевод");
    RU.put(R.string.Tgx101SpeechSection, "Распознавание речи");
    RU.put(R.string.Tgx101SpeechModel, "Голосовые в текст на телефоне");
    RU.put(R.string.Tgx101SpeechModelHint, "Если Telegram не расшифровывает голосовое (нет Премиума, недельные пробные расшифровки закончились), а служба распознавания телефона не справляется, оно распознаётся на телефоне скачанной моделью, без интернета.");
    RU.put(R.string.Tgx101SpeechModelNone, "Выключено");
    RU.put(R.string.Tgx101SpeechModelLight, "Лёгкая, русский (29 МБ)");
    RU.put(R.string.Tgx101SpeechModelAccurate, "Точная, русский, со знаками препинания — GigaAM (215 МБ)");
    RU.put(R.string.Tgx101SpeechModelDownload, "Скачать");
    RU.put(R.string.Tgx101SpeechModelDownloading, "Скачивается… %1$d%%");
    RU.put(R.string.Tgx101SpeechModelInUse, "Используется");
    RU.put(R.string.Tgx101SpeechModelUse, "Использовать");
    RU.put(R.string.Tgx101SpeechModelDelete, "Удалить с телефона");
    RU.put(R.string.Tgx101SpeechModelDownloadFailed, "Не удалось скачать модель. Проверьте соединение и попробуйте ещё раз");
    RU.put(R.string.Tgx101SpeechModelMissing, "Чтобы расшифровывать голосовые на телефоне, скачайте модель: Настройки → MagiX → Распознавание речи");
    RU.put(R.string.Tgx101MenuThread, "Посмотреть в теме / ответы");
    RU.put(R.string.Tgx101MenuBack, "Назад");
    RU.put(R.string.Tgx101PlayerChapters, "Главы");
    RU.put(R.string.Tgx101BackgroundSet, "%1$s установил(а) новый фон чата");
    RU.put(R.string.Tgx101BackgroundSet_outgoing, "Вы установили новый фон чата");
    RU.put(R.string.Tgx101BackgroundSetSelf_outgoing, "Вы установили новый фон только для себя");
    RU.put(R.string.Tgx101SuggestPhoto, "%1$s предлагает вам новое фото профиля");
    RU.put(R.string.Tgx101SuggestPhoto_outgoing, "Вы предложили новое фото профиля");
    RU.put(R.string.Tgx101SuggestBirthdate, "%1$s предлагает указать дату рождения: %2$s");
    RU.put(R.string.Tgx101SuggestBirthdate_outgoing, "Вы предложили дату рождения: %1$s");
    RU.put(R.string.Tgx101UsersShared, "Вы поделились пользователем с ботом");
    RU.put(R.string.Tgx101ChatShared, "Вы поделились чатом с ботом");
    RU.put(R.string.Tgx101PassportSent, "Вы передали боту данные Telegram Passport");
    RU.put(R.string.Tgx101PlainText, "%1$s");
    RU.put(R.string.Tgx101GiftSent, "%1$s отправил(а) подарок %2$s");
    RU.put(R.string.Tgx101GiftSent_outgoing, "Вы отправили подарок %1$s");
    RU.put(R.string.Tgx101GiftUpgraded, "Улучшенный подарок %1$s");
    RU.put(R.string.Tgx101GiftRefunded, "Подарок возвращён");
    RU.put(R.string.Tgx101GiftOffer, "Предложение купить подарок %1$s");
    RU.put(R.string.Tgx101GiftOfferRejected, "Предложение купить %1$s отклонено");
    RU.put(R.string.Tgx101GramsSent, "%1$s отправил(а) Grams");
    RU.put(R.string.Tgx101GramsSent_outgoing, "Вы отправили Grams");
    RU.put(R.string.Tgx101StakeDice, "🎲 Кубик со ставкой: выпало %1$s");
    RU.put(R.string.Tgx101GroupCallActive, "%1$s приглашает в групповой звонок");
    RU.put(R.string.Tgx101GroupCallActive_outgoing, "Идёт групповой звонок");
    RU.put(R.string.Tgx101GroupCallMissed, "Пропущенный групповой звонок");
    RU.put(R.string.Tgx101GroupCallEnded, "Групповой звонок%1$s");
    RU.put(R.string.Tgx101SuggestedPostApproved, "Предложенный пост одобрен");
    RU.put(R.string.Tgx101SuggestedPostApprovalFailed, "Не удалось одобрить предложенный пост");
    RU.put(R.string.Tgx101SuggestedPostDeclined, "Предложенный пост отклонён");
    RU.put(R.string.Tgx101SuggestedPostPaid, "Предложенный пост оплачен");
    RU.put(R.string.Tgx101SuggestedPostRefunded, "Оплата предложенного поста возвращена");
    RU.put(R.string.Tgx101StoryMessage, "📖 История (пока открывается в официальном приложении)");
    RU.put(R.string.Tgx101DefaultAutoDelete, "Автоудаление в новых чатах");
    RU.put(R.string.Tgx101DefaultAutoDeleteHint, "Сообщения в чатах, которые вы начнёте с этого момента, будут удаляться у всех через это время. Уже существующие чаты не меняются.");
    RU.put(R.string.Tgx101AutoDeleteOff, "Выключено");
    RU.put(R.string.Tgx101UserNote, "Заметка");
    RU.put(R.string.Tgx101UserNoteHint, "Видна только вам");
    RU.put(R.string.Tgx101UserNoteAdd, "Добавить заметку (видна только вам)");
    RU.put(R.string.Tgx101SharePin, "Закрепить в первых строках");
    RU.put(R.string.Tgx101ShareUnpin, "Открепить из первых строк");
    RU.put(R.string.Tgx101SharePinned, "Закреплено: при следующем «Поделиться» чат будет в первых строках");
    RU.put(R.string.Tgx101ShareUnpinned, "Откреплено");
    RU.put(R.string.Tgx101SharePinFull, "Две первые строки заполнены — сначала открепите какой-нибудь чат");
    RU.put(R.string.Tgx101NameColor, "Цвет имени");
    RU.put(R.string.Tgx101NameColorHint, "Цвет вашего имени в группах, ответов вам и ваших превью ссылок");
    RU.put(R.string.Tgx101NameColorOther, "Другой");
    RU.put(R.string.Tgx101ColorRed, "Красный");
    RU.put(R.string.Tgx101ColorOrange, "Оранжевый");
    RU.put(R.string.Tgx101ColorViolet, "Фиолетовый");
    RU.put(R.string.Tgx101ColorGreen, "Зелёный");
    RU.put(R.string.Tgx101ColorCyan, "Голубой");
    RU.put(R.string.Tgx101ColorBlue, "Синий");
    RU.put(R.string.Tgx101ColorPink, "Розовый");
    RU.put(R.string.Tgx101LocalPin, "Закрепить на этом телефоне");
    RU.put(R.string.Tgx101LocalUnpin, "Открепить (на телефоне)");
    RU.put(R.string.Tgx101LocalPinned, "Закреплено на этом телефоне: лимит закреплённых чатов Telegram исчерпан, на других устройствах чат не будет закреплён");
    RU.put(R.string.Tgx101SavedByChats, "Избранное по чатам");
    RU.put(R.string.Tgx101SavedMyNotes, "Мои заметки");
    RU.put(R.string.Tgx101SavedAuthorHidden, "Скрытый отправитель");
    RU.put(R.string.Tgx101TranslateModels, "Словари на телефоне");
    RU.put(R.string.Tgx101TranslateModelsNone, "Словарей пока нет. Каждый язык скачивается один раз, при первом переводе с него или на него, — примерно %1$d МБ каждый (английский встроен).");
    RU.put(R.string.Tgx101TranslateModelsHint, "Скачанные словари занимают около %1$d МБ. Нажмите на словарь, чтобы удалить его — при необходимости он скачается снова.");
    RU.put(R.string.Tgx101Megabytes, "МБ");
    RU.put(R.string.Tgx101TranslateModelDeleted, "Словарь удалён");
    RU.put(R.string.Tgx101TranslateDownloading, "Скачивается словарь «%1$s» (≈%2$d МБ), только один раз");
    RU.put(R.string.Tgx101SavedEmpty, "В Избранном пока ничего нет");
    RU.put(R.string.Tgx101ChatBackground, "Фон чата");
    RU.put(R.string.Tgx101ChatBackgroundHint, "Фон, выбранный в Настройках → Настройки чатов, ставится только для этого чата");
    RU.put(R.string.Tgx101ChatBackgroundSelf, "Поставить текущий фон для себя");
    RU.put(R.string.Tgx101ChatBackgroundBoth, "Поставить текущий фон для обоих");
    RU.put(R.string.Tgx101ChatBackgroundReset, "Сбросить фон чата");
    RU.put(R.string.Tgx101ChatBackgroundNone, "Сначала выберите фон в настройках чатов");
    RU.put(R.string.Tgx101WebAppSubtitle, "мини-приложение");
    RU.put(R.string.Tgx101WebAppReload, "Перезагрузить");
    RU.put(R.string.Tgx101WebAppNoPayments, "Оплата внутри мини-приложений пока не поддерживается");
    RU.put(R.string.Tgx101WebAppClose, "Закрыть");
    RU.put(R.string.Tgx101ReleaseToClose, "Отпустите, чтобы закрыть");
    RU.put(R.string.Tgx101ZoomPullClose, "Свайп вниз закрывает зум фото");
    RU.put(R.string.Tgx101FilterHideFully, "Скрывать полностью");
    RU.put(R.string.Tgx101FilterHideFullyHint, "Без полоски «Скрыто фильтром»: такие сообщения совсем не показываются в чате. Ничего не удаляется: поиск их находит.");
    RU.put(R.string.Tgx101HideChannelReactions, "Скрывать реакции под постами каналов");
    RU.put(R.string.Tgx101NextChannelSwipe, "Свайп к следующему каналу");
    RU.put(R.string.Tgx101NextChannelPull, "↑ Дальше: %1$s");
    RU.put(R.string.Tgx101NextChannelRelease, "Отпустите — откроется %1$s");
    RU.put(R.string.Tgx101NextChannelNone, "Непрочитанных каналов нет");
    RU.put(R.string.Tgx101CaptionAbove, "Текст над медиа");
    RU.put(R.string.Tgx101SendHd, "HD-качество");
    RU.put(R.string.Tgx101MyStory, "Моя история");
    RU.put(R.string.Tgx101StoryIncognito, "Инкогнито");
    RU.put(R.string.Tgx101StoryIncognitoOn, "Инкогнито включено: ваши просмотры за последние 5 и следующие 25 минут скрыты");
    RU.put(R.string.Tgx101StoryReply, "Ответить…");
    RU.put(R.string.Tgx101StoryReplySent, "Ответ отправлен");
    RU.put(R.string.Tgx101StoryHide, "Скрыть истории");
    RU.put(R.string.Tgx101StoryShowLess, "Показывать меньше (в конец)");
    RU.put(R.string.Tgx101StoryShowNormally, "Показывать как обычно");
    RU.put(R.string.Tgx101StoryNotifyOn, "Уведомлять о новых историях");
    RU.put(R.string.Tgx101StoryNotifyOff, "Не уведомлять о новых историях");
    RU.put(R.string.Tgx101StoryNotifyOnDone, "Будут уведомления о новых историях");
    RU.put(R.string.Tgx101StoryNotifyOffDone, "Уведомлений о новых историях не будет");
    RU.put(R.string.Tgx101ScheduledDone, "Сообщение запланировано");
    RU.put(R.string.Tgx101StoryProfile, "Просмотр профиля");
    RU.put(R.string.Tgx101StoriesMode, "Истории");
    RU.put(R.string.Tgx101StoriesModeStrip, "Лента над чатами");
    RU.put(R.string.Tgx101StoriesModeRings, "Кольца на аватарках");
    RU.put(R.string.Tgx101StoriesModeRestart, "Применится, когда вернётесь к списку чатов");
    RU.put(R.string.Tgx101StoriesFolders, "Истории из папок");
    RU.put(R.string.Tgx101StoriesFoldersAll, "Все чаты");
    RU.put(R.string.Tgx101StoriesFoldersNone, "Никакие");
    RU.put(R.string.Tgx101StoriesFoldersHint, "Показывать истории только чатов из выбранных папок. «Никакие» убирает ленту и кольца.");
    RU.put(R.string.Tgx101TestSection, "Тесты");
    RU.put(R.string.Tgx101FakeNoPremium, "Как без Премиума (тест)");
    RU.put(R.string.Tgx101FakeNoPremiumHint, "Только в тестовых сборках. Приложение показывает всё как для аккаунта без Премиума; сервер по-прежнему знает, что Премиум есть. После переключения перезапустите приложение.");
    RU.put(R.string.Tgx101TranslateOnDevice, "Переводить на телефоне (Google)");
    RU.put(R.string.Tgx101TranslateOnDeviceHint, "Сообщения переводит Google ML Kit прямо на телефоне, а не сервер Telegram. Каждый язык скачивается один раз (около 30 МБ), дальше перевод работает без интернета. Языки, которых он не знает, переводит Telegram, как раньше.");
    RU.put(R.string.Tgx101PlayerSection, "Видеоплеер");
    RU.put(R.string.Tgx101PlayerGestures, "Жесты");
    RU.put(R.string.Tgx101PlayerGesturesHint, "Жесты плеера. Если включена перемотка свайпом, двойное нажатие по краям больше не перематывает.");
    RU.put(R.string.Tgx101PlayerBrightness, "Яркость");
    RU.put(R.string.Tgx101PlayerSpeed, "Скорость");
    RU.put(R.string.Tgx101PlayerSettings, "Настройки плеера");
    RU.put(R.string.Tgx101PlayerGuide, "Обучение");
    RU.put(R.string.Tgx101GuideTitle, "Жесты в плеере");
    RU.put(R.string.Tgx101GuideOk, "Понятно");
    RU.put(R.string.Tgx101GuideText, "Свайп вверх-вниз в левой трети — яркость (если включено в «Жестах»).\nСвайп вверх-вниз в правой трети — громкость (если включено в «Жестах»).\nСвайп вниз в средней трети — свернуть видео.\nСвайп влево-вправо в середине — перемотка с подсказкой, на сколько (если включено в «Жестах»). Если выключено — двойное касание слева или справа мотает назад или вперёд.\nСвайп влево-вправо от самого края экрана — предыдущий или следующий файл.\nДвойное касание по центру — пауза / продолжить.\nНажать и держать — скорость 2×, пока держите (если включено в «Жестах»).\nОдно касание в любом месте — показать или спрятать кнопки: пауза, время, скорость, замок, настройки.\nВерхний край экрана — это шторка уведомлений, видео на него не реагирует.");
    RU.put(R.string.Tgx101PlayerSeekStep, "Шаг перемотки");
    RU.put(R.string.Tgx101PlayerLoop, "Повтор видео");
    RU.put(R.string.Tgx101PlayerPauseMusic, "Пауза музыки");
    RU.put(R.string.Tgx101GestureSeek, "Перемотка");
    RU.put(R.string.Tgx101GestureBrightness, "Яркость");
    RU.put(R.string.Tgx101GestureVolume, "Громкость");
    RU.put(R.string.Tgx101GestureSpeed, "Скорость 2×");
    RU.put(R.string.Tgx101PlayerResume, "Продолжать с места");
    RU.put(R.string.Tgx101PlayerSleep, "Таймер сна");
    RU.put(R.string.Tgx101Orientation, "Ориентация");
    RU.put(R.string.Tgx101Rotate, "Повернуть экран");
    RU.put(R.string.Tgx101OrientationHint, "Ориентация экрана в плеере");
    RU.put(R.string.Tgx101OrientationSystem, "Как в системе");
    RU.put(R.string.Tgx101OrientationAuto, "Автоповорот (даже если в системе выключен)");
    RU.put(R.string.Tgx101OrientationPortrait, "Только вертикально (горизонталь — кнопкой)");
    RU.put(R.string.Tgx101OrientationSystemShort, "система");
    RU.put(R.string.Tgx101OrientationAutoShort, "авто");
    RU.put(R.string.Tgx101OrientationPortraitShort, "вертик.");
    RU.put(R.string.Tgx101On, "вкл");
    RU.put(R.string.Tgx101Off, "выкл");
    RU.put(R.string.Tgx101Seconds, "%1$d с");
    RU.put(R.string.Tgx101Minutes, "%1$d мин");
    RU.put(R.string.Tgx101PlayerLock, "Заблокировать экран");
    RU.put(R.string.Tgx101PlayerLockedHint, "Экран заблокирован.\nУдерживайте 2 с, чтобы снять");
    RU.put(R.string.Tgx101PlayerVolume, "Громкость");
    RU.put(R.string.ShowCommentsButton, "Кнопка комментариев под постами");
    RU.put(R.string.HideSubscribeLink, "Скрывать «Подписаться» под постами");
    RU.put(R.string.SeparateChannelPosts, "Отступ и линия между постами");
    RU.put(R.string.ChannelButtonsHint, "Без кнопки «Обсудить» группа обсуждения открывается из меню канала ⋮. Без кнопки комментариев комментарии открываются из меню поста. Без кнопки уведомлений звук канала включается и выключается в меню ⋮. Чтобы изменения применились, откройте канал заново. «Подписаться» убирается, только если это последняя строка поста и ссылка ведёт на этот же канал.");
    RU.put(R.string.ProxyPaste, "Вставить из буфера");
    RU.put(R.string.ProxyPasteNothing, "В буфере обмена нет ссылок на прокси");
    RU.put(R.string.ProxyPasteResult, "Добавлено прокси: %1$d, уже были в списке: %2$d");
    RU.put(R.string.ProxyCopyAll, "Скопировать все прокси");
    RU.put(R.string.ProxyCopyAllNothing, "Нет прокси, которыми можно поделиться ссылкой");
    RU.put(R.string.ProxyCopyAllResult, "Скопировано ссылок на прокси: %1$d");
    RU.put(R.string.ProxyCopyAllResultHttp, "Скопировано ссылок на прокси: %1$d. HTTP-прокси (%2$d) нельзя передать ссылкой");
    RU.put(R.string.ProxyRemoveUnavailable, "Удалить неработающие");
    RU.put(R.string.ProxyRemoveUnavailableConfirm, "Не ответили при повторной проверке: %1$d. Удалить их?");
    RU.put(R.string.ProxyCheckingAll, "Проверяю прокси…");
    RU.put(R.string.ProxyCheckNoNetwork, "Ничего не отвечает. Проверьте подключение к интернету");
    RU.put(R.string.ProxyAllAvailable, "Все прокси отвечают");
    RU.put(R.string.ProxyShowQr, "QR-код");
    RU.put(R.string.ProxyReturnDirect, "Возвращаться на прямое соединение");
    RU.put(R.string.ProxyHideSponsor, "Скрывать канал спонсора прокси");
    RU.put(R.string.ProxyAutoSwitchHintTgx101, "Переключать автоматически: если приложение долго не может подключиться, оно пробует другие прокси и прямое соединение. Возвращаться на прямое соединение: после смены сети (Wi-Fi, мобильная), если Telegram работает без прокси, прокси выключается. Не включайте, если провайдер замедляет Telegram: проверка этого не заметит. Скрывать канал спонсора прокси: канал, который владелец прокси закрепляет в списке чатов, не показывается. Применится после перезапуска приложения.");
    RU.put(R.string.ChatExport, "Экспорт чата");
    RU.put(R.string.TranslateWholeChat, "Перевести чат");
    RU.put(R.string.TranslateWholeChatOff, "Показать оригинал");
    RU.put(R.string.InvoicePrice, "Счёт: %1$s");
    RU.put(R.string.InvoicePaid, "Оплачено: %1$s");
    RU.put(R.string.InvoicePay, "Оплатить %1$s");
    RU.put(R.string.PaidMediaLocked, "🔒 Платный пост: %1$s");
    RU.put(R.string.PaidMediaUnlock, "Открыть за %1$s");
    RU.put(R.string.PaidMediaPartial, "Показано: 1 из %1$d");
    RU.put(R.string.StarsPayConfirm, "Оплатить «%1$s» — %2$s?\nНа балансе: %3$s");
    RU.put(R.string.StarsSubscribeConfirm, "Подписка «%1$s»: %2$s в месяц. Оформить?\nНа балансе: %3$s");
    RU.put(R.string.StarsNotEnough, "Не хватает звёзд: нужно %1$s, на балансе %2$s. Купить звёзды можно на Fragment или в официальном Telegram.");
    RU.put(R.string.StarsOpenFragment, "Открыть Fragment");
    RU.put(R.string.StarsPaid, "Оплачено");
    RU.put(R.string.StarsPayFailed, "Не удалось оплатить: %1$s");
    RU.put(R.string.Tgx101Stars, "Звёзды Telegram");
    RU.put(R.string.Tgx101StarsBalance, "Баланс");
    RU.put(R.string.Tgx101StarsBuy, "Купить звёзды на Fragment");
    RU.put(R.string.Tgx101StarsBuyHint, "Оплатите банковской картой прямо здесь или купите на Fragment за TON. Звёзды можно тратить в ботах и каналах.");
    RU.put(R.string.Tgx101StarsBuyHeader, "Купить звёзды");
    RU.put(R.string.Tgx101StarsBuyMore, "Другие пакеты");
    RU.put(R.string.Tgx101StarsPremiumBot, "Купить через @PremiumBot");
    RU.put(R.string.Tgx101StarsHistory, "История");
    RU.put(R.string.Tgx101StarsHistoryEmpty, "Операций пока нет");
    RU.put(R.string.Tgx101StarsMore, "Показать ещё");
    RU.put(R.string.Tgx101StarsRefund, "возврат");
    RU.put(R.string.Tgx101StarsKindDeposit, "пополнение");
    RU.put(R.string.Tgx101StarsKindWithdrawal, "вывод");
    RU.put(R.string.Tgx101StarsKindSubscription, "подписка");
    RU.put(R.string.Tgx101StarsKindGift, "подарок");
    RU.put(R.string.Tgx101StarsKindReaction, "реакция");
    RU.put(R.string.Tgx101StarsKindPaidMedia, "платный пост");
    RU.put(R.string.Tgx101StarsKindSale, "продажа");
    RU.put(R.string.Tgx101StarsKindPurchase, "покупка");
    RU.put(R.string.PaidReactionHint, "Поддержать пост звёздами. Их получит автор, под постом появится ваша звёздная реакция.\nНа балансе: %1$s");
    RU.put(R.string.PaidReactionSent, "Отправлено: %1$s");
    RU.put(R.string.StarsCardUnsupported, "Этот способ оплаты в PlumaGram не поддерживается: оплатите в официальном Telegram.");
    RU.put(R.string.ChatExportFormatHint, "Вся история чата сохранится в «Загрузки/PlumaGram» одним файлом. Только текст: фото, видео и голосовые отмечаются как [Фото] и т. п.");
    RU.put(R.string.ChatExportHtml, "Веб-страница (HTML) — для чтения");
    RU.put(R.string.ChatExportTxt, "Обычный текст (TXT)");
    RU.put(R.string.ChatExportProgress, "Загружено сообщений: %1$d");
    RU.put(R.string.ChatExportHeader, "Сообщений: %1$d · экспорт %2$s");
    RU.put(R.string.ChatExportForwarded, "Переслано от %1$s");
    RU.put(R.string.ChatExportDone, "Экспортировано сообщений: %1$d\n%2$s");
    RU.put(R.string.ChatExportFailed, "Не удалось экспортировать: %1$s");
    RU.put(R.string.ChatImport, "Импортировать чат");
    RU.put(R.string.ChatImportHint, "Это выгрузка чата из другого мессенджера. Её можно импортировать в чат Telegram.");
    RU.put(R.string.ChatImportPrivateHint, "Это выгрузка чата WhatsApp с %1$s. Её можно импортировать в ваш чат Telegram с этим человеком: сообщения появятся со своими датами и пометкой «импортировано».");
    RU.put(R.string.ChatImportGroupHint, "Это выгрузка группы WhatsApp «%1$s». Её можно импортировать в группу Telegram, где вы администратор: сообщения появятся со своими датами и пометкой «импортировано».");
    RU.put(R.string.ChatImportSendAsFiles, "Отправить как файлы");
    RU.put(R.string.ChatImportPick, "Импортировать в…");
    RU.put(R.string.ChatImportPickPrivate, "Выберите личный чат с этим человеком");
    RU.put(R.string.ChatImportPickGroup, "Выберите группу, где вы администратор");
    RU.put(R.string.ChatImportConfirm, "Импортировать в «%1$s»?");
    RU.put(R.string.ChatImportProgress, "Загружаю чат и файлов: %1$d… Это может занять время, не закрывайте приложение.");
    RU.put(R.string.ChatImportDone, "Чат импортирован в «%1$s»");
    RU.put(R.string.ChatImportFailed, "Не удалось импортировать: %1$s");
    RU.put(R.string.Tgx101Updates, "Обновления");
    RU.put(R.string.Tgx101CheckUpdates, "Сообщать о новых версиях");
    RU.put(R.string.Tgx101CheckUpdatesHint, "Раз в день при открытии приложение проверяет на GitHub, не вышла ли новая версия PlumaGram, и показывает уведомление со ссылками на GitHub и 4PDA. Ничего не скачивается и не устанавливается само.");
    RU.put(R.string.Tgx101UpdateChannel, "Обновления PlumaGram");
    RU.put(R.string.Tgx101UpdateTitle, "Вышла PlumaGram %1$s");
    RU.put(R.string.Tgx101UpdateText, "Нажмите, чтобы скачать новую версию");
    RU.put(R.string.OpenInBrowser, "Открыть в браузере");
    RU.put(R.string.UnsupportedKindStory, "история");
    RU.put(R.string.UnsupportedKindPaidMedia, "платное фото или видео");
    RU.put(R.string.UnsupportedKindChecklist, "список задач");
    RU.put(R.string.UnsupportedKindStakeDice, "ставка на кубик");
    RU.put(R.string.UnsupportedKindGroupCall, "групповой звонок");
    RU.put(R.string.UnsupportedKindGift, "подарок");
    RU.put(R.string.UnsupportedKindGiveaway, "приз розыгрыша");
    RU.put(R.string.UnsupportedKindShared, "выбранные чаты или пользователи");
    RU.put(R.string.RichMessageOpen, "Открыть пост");
    RU.put(R.string.RichMessageOpenHint, "Пост с фото и кнопками. Нажмите, чтобы открыть.");
    RU.put(R.string.RichMessageOpenFull, "Открыть пост полностью ›");
    RU.put(R.string.RichMessageOpenFailed, "Не удалось загрузить пост: %1$s");
    RU.put(R.string.RichMessageOpenUnsupported, "В посте есть элементы, которые просмотрщик пока не умеет показывать");
  }

  /** Russian text for a mod string when the app language is Russian, otherwise null. */
  static @Nullable String localized (@Nullable TdApi.LanguagePackInfo languagePackInfo, int resId) {
    String text = RU.get(resId);
    if (text == null || !isRussian(languagePackInfo)) {
      return null;
    }
    return text;
  }

  private static boolean isRussian (@Nullable TdApi.LanguagePackInfo info) {
    return info != null && (startsWithRu(info.id) || startsWithRu(info.baseLanguagePackId) || startsWithRu(info.pluralCode));
  }

  private static boolean startsWithRu (@Nullable String code) {
    return code != null && (code.equals("ru") || code.startsWith("ru-") || code.startsWith("ru_"));
  }
}
